openapi: 3.0.0
info:
  title: Docusaurus RAG Chatbot API
  description: API for the Docusaurus RAG Chatbot UI to communicate with backend services
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /api/chat/send:
    post:
      summary: Send a message to the RAG system
      description: Sends a user message to the backend RAG system and returns an AI response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - sessionId
              properties:
                message:
                  type: string
                  description: The user's message
                  example: "What are the key principles of embodied AI?"
                sessionId:
                  type: string
                  description: Unique identifier for the conversation session
                  example: "sess_abc123xyz"
                selectedText:
                  type: string
                  description: Optional text selected by the user for context
                  example: "Embodied AI refers to artificial intelligence systems that interact with the physical world through sensors and actuators."
                context:
                  type: object
                  description: Additional context for the query
                  properties:
                    currentPage:
                      type: string
                      description: URL or identifier of the current page
                      example: "/chapters/embodied-ai/introduction"
      responses:
        '200':
          description: Successful response from the AI
          content:
            application/json:
              schema:
                type: object
                required:
                  - response
                  - sources
                  - sessionId
                properties:
                  response:
                    type: string
                    description: The AI-generated response
                    example: "Embodied AI refers to artificial intelligence systems that interact with the physical world through sensors and actuators..."
                  sources:
                    type: array
                    items:
                      type: string
                    description: References to book sections used in the response
                    example: ["/chapters/embodied-ai/introduction", "/chapters/embodied-ai/principles"]
                  sessionId:
                    type: string
                    description: The session identifier (may be updated by server)
                    example: "sess_abc123xyz"
                  contextUsed:
                    type: string
                    description: Text from selectedText that was used in the response
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/chat/session:
    post:
      summary: Create a new chat session
      description: Initializes a new conversation session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                initialContext:
                  type: object
                  description: Initial context for the session
      responses:
        '200':
          description: Session created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - sessionId
                properties:
                  sessionId:
                    type: string
                    description: Unique identifier for the new session
                    example: "sess_new456def"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get session details
      description: Retrieves information about an existing session
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            type: string
          description: The session identifier
      responses:
        '200':
          description: Session information
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                    example: "sess_abc123xyz"
                  isActive:
                    type: boolean
                    description: Whether the session is currently active
                  messageCount:
                    type: number
                    description: Number of messages in the session
                  lastActiveAt:
                    type: string
                    format: date-time
                    description: When the session was last active
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "BAD_REQUEST"
        message:
          type: string
          description: Human-readable error message
          example: "Message cannot be empty"